SET DEFINE OFF

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Adam', 'Abacki', NULL, 'Mokotow');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Edward', 'Babacki', 'edward.b@adres.pl', 'Praga');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Franciszek', 'Cabacki', NULL, NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Michal', 'Dabacki', 'michal.d@adres.pl', NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Jan', 'Ebacki', NULL, 'Targowek');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Ewa', 'Fabacka', 'ewa.f@adres.pl', 'Wola');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Aleksandra', 'Gabacka', NULL, NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Joanna', 'Habacka', 'joanna.h@adres.pl', NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Julia', 'Ibacka', NULL, 'Ursynow');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Wiktoria', 'Kabacka', 'wiktoria.k@adres.pl', 'Bielany');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Pawel', 'Labacka', NULL, NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Krzysztof', 'Mabacki', 'krzysztof.m@adres.pl', NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Karol', 'Nabacki', NULL, 'Ursus');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Lukasz', 'Obacki', 'lukasz.o@adres.pl', 'Wlochy');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Dominik', 'Pabacki', NULL, NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Klaudia', 'Rabacki', 'klaudia.r@adres.pl', NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Katarzyna', 'Sabacka', NULL, 'Goclaw');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Zofia', 'Tabacka', 'zofia.t@adres.pl', 'Zoliborz');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Kamila', 'Wabacka', NULL, NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Marta', 'Zabacka', 'marta.z@adres.pl', NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Adam', 'Bebacki', NULL, 'Bialoleka');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Edward', 'Cebacki', NULL, 'Srodmiescie');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Franciszek', 'Debacki', 'franiszek.d@adres.pl', NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Michal', 'Febacki', NULL, NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Jan', 'Gebacki', 'jan.g@adres.pl', 'Bemowo');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Ewa', 'Hebacka', NULL, 'Ochota');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Aleksandra', 'Kebacka', 'aleksandra.k@adres.pl', NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Joanna', 'Lebacka', NULL, NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Julia', 'Mebacka', 'julia.m@adres.pl', 'Mokotow');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Wiktoria', 'Nebacka', NULL, 'Praga');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Pawel', 'Pebacki', 'pawel.p@adres.pl', NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Krzysztof', 'Rebacki', NULL, NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Karol', 'Sebacki', 'karol.s@adres.pl', 'Targowek');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Lukasz', 'Tebacki', NULL, 'Wola');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Dominik', 'Webacki', 'dominik.w@adres.pl', NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Klaudia', 'Zebacka', NULL, NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Katarzyna', 'Bobacka', 'katarzyna.b@adres.pl', 'Ursynow');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Zofia', 'Cobacka', NULL, 'Bielany');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Kamila', 'Dobacka', 'kamila.d@adres.pl', NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Marta', 'Fobacka', NULL, NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Adam', 'Gobacki', 'adam.g@adres.pl', 'Ursus');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Edward', 'Hobacki', 'edward.h@adres.pl', 'Wlochy');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Franciszek', 'Kobacki', NULL, NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Michal', 'Lobacki', 'michal.l@adres.pl', NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Jan', 'Mobacki', NULL, 'Goclaw');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Ewa', 'Nobacka', 'ewa.n@adres.pl', 'Zoliborz');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Aleksandra', 'Pobacka', NULL, NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Joanna', 'Sobacka', 'joanna.s@adres.pl', NULL);

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Julia', 'Tobacka', NULL, 'Bialoleka');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Wiktoria', 'Wobacka', 'wiktoria.w@adres.pl', 'Srodmiescie');

INSERT INTO KURSANT (IMIE, NAZWISKO, ADRES_EMAIL, PREFEROWANA_LOKALIZACJA) 
VALUES ('Pawel', 'Zobacki', NULL, NULL);

COMMIT;