SET DEFINE OFF

INSERT INTO KATEGORIA (TYP_KATEGORII) 
VALUES ('AM');

INSERT INTO KATEGORIA (TYP_KATEGORII) 
VALUES ('A1');

INSERT INTO KATEGORIA (TYP_KATEGORII) 
VALUES ('A2');

INSERT INTO KATEGORIA (TYP_KATEGORII) 
VALUES ('A');

INSERT INTO KATEGORIA (TYP_KATEGORII) 
VALUES ('B1');

INSERT INTO KATEGORIA (TYP_KATEGORII) 
VALUES ('B');

INSERT INTO KATEGORIA (TYP_KATEGORII) 
VALUES ('C1');

INSERT INTO KATEGORIA (TYP_KATEGORII) 
VALUES ('C');

INSERT INTO KATEGORIA (TYP_KATEGORII) 
VALUES ('D1');

INSERT INTO KATEGORIA (TYP_KATEGORII) 
VALUES ('D');

INSERT INTO KATEGORIA (TYP_KATEGORII) 
VALUES ('BE');

INSERT INTO KATEGORIA (TYP_KATEGORII) 
VALUES ('C1E');

INSERT INTO KATEGORIA (TYP_KATEGORII) 
VALUES ('CE');

INSERT INTO KATEGORIA (TYP_KATEGORII) 
VALUES ('D1E');

INSERT INTO KATEGORIA (TYP_KATEGORII) 
VALUES ('DE');

INSERT INTO KATEGORIA (TYP_KATEGORII) 
VALUES ('T');

COMMIT;