SET DEFINE OFF

INSERT INTO INSTRUKTOR (IMIE, NAZWISKO, PREFEROWANA_LOKALIZACJA) 
VALUES ('Jozef', 'Bubacki', 'Mokotow');

INSERT INTO INSTRUKTOR (IMIE, NAZWISKO, PREFEROWANA_LOKALIZACJA) 
VALUES ('Krzysztof', 'Fubacki', 'Praga');

INSERT INTO INSTRUKTOR (IMIE, NAZWISKO, PREFEROWANA_LOKALIZACJA) 
VALUES ('Karol', 'Gubacki', 'Bemowo');

INSERT INTO INSTRUKTOR (IMIE, NAZWISKO, PREFEROWANA_LOKALIZACJA) 
VALUES ('Lukasz', 'Pubacki', 'Ochota');

INSERT INTO INSTRUKTOR (IMIE, NAZWISKO, PREFEROWANA_LOKALIZACJA) 
VALUES ('Dominik', 'Rubacki', 'Targowek');

INSERT INTO INSTRUKTOR (IMIE, NAZWISKO, PREFEROWANA_LOKALIZACJA) 
VALUES ('Klaudia', 'Dubacka', 'Wola');

INSERT INTO INSTRUKTOR (IMIE, NAZWISKO, PREFEROWANA_LOKALIZACJA) 
VALUES ('Katarzyna', 'Lubacka', 'Zoliborz');

INSERT INTO INSTRUKTOR (IMIE, NAZWISKO, PREFEROWANA_LOKALIZACJA) 
VALUES ('Zofia', 'Mubacka', 'Ursynow');

INSERT INTO INSTRUKTOR (IMIE, NAZWISKO, PREFEROWANA_LOKALIZACJA) 
VALUES ('Kamila', 'Nubacka', 'Bielany');

INSERT INTO INSTRUKTOR (IMIE, NAZWISKO, PREFEROWANA_LOKALIZACJA) 
VALUES ('Marta', 'Rubacka', 'Bemowo');

COMMIT;