SET DEFINE OFF

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Samochod osobowy', 'Hyundai', 'i20', 2018.0, 'AKTUALNY', to_date('12/01/2025', 'DD/MM/YYYY'), NULL, 'B');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Samochod osobowy', 'Hyundai', 'i20', 2019.0, 'AKTUALNY', to_date('10/02/2025', 'DD/MM/YYYY'), NULL, 'B');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Samochod osobowy', 'Hyundai', 'i20', 2019.0, 'AKTUALNY', to_date('4/06/2024', 'DD/MM/YYYY'), NULL, 'B');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Samochod osobowy', 'Hyundai', 'i20', 2021.0, 'NIEAKTUALNY', to_date('25/01/2024', 'DD/MM/YYYY'), NULL, 'B');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Samochod osobowy', 'Hyundai', 'i20', 2022.0, 'AKTUALNY', to_date('12/10/2024', 'DD/MM/YYYY'), NULL, 'B');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Samochod osobowy', 'Hyundai', 'i20', 2020.0, 'AKTUALNY', to_date('8/04/2024', 'DD/MM/YYYY'), NULL, 'B');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Samochod osobowy', 'Hyundai', 'i20', 2020.0, 'AKTUALNY', to_date('14/08/2024', 'DD/MM/YYYY'), NULL, 'B');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Samochod osobowy', 'Hyundai', 'i20', 2019.0, 'NIEAKTUALNY', to_date('22/01/2024', 'DD/MM/YYYY'), NULL, 'B');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Motocykl', 'Suzuki', 'SV 650', 2019.0, 'AKTUALNY', to_date('4/02/2025', 'DD/MM/YYYY'), NULL, 'A');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Motocykl', 'Suzuki', 'SV 650', 2022.0, 'AKTUALNY', to_date('12/01/2025', 'DD/MM/YYYY'), NULL, 'A');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Motocykl', 'Suzuki', 'SFV 650UA 35kW', 2021.0, 'AKTUALNY', to_date('14/08/2024', 'DD/MM/YYYY'), NULL, 'A2');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Motocykl', 'Suzuki ', 'SFV 650UA 35kW', 2021.0, 'AKTUALNY', to_date('8/04/2024', 'DD/MM/YYYY'), NULL, 'A2');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Motocykl', 'Suzuki ', 'SFV 650UA 35kW', 2020.0, 'NIEAKTUALNY', to_date('18/01/2024', 'DD/MM/YYYY'), NULL, 'A2');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Motocykl', 'Honda ', 'CBF 125M', 2022.0, 'AKTUALNY', to_date('8/04/2024', 'DD/MM/YYYY'), NULL, 'A1');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Motorower', 'Romet ', 'Zetka 50', 2020.0, 'AKTUALNY', to_date('4/06/2024', 'DD/MM/YYYY'), NULL, 'AM');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Motorower', 'Kymco ', 'Agility 50', 2019.0, 'AKTUALNY', to_date('10/02/2025', 'DD/MM/YYYY'), NULL, 'AM');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Samochod', 'Renault ', 'Trafic', 2018.0, 'AKTUALNY', to_date('12/01/2025', 'DD/MM/YYYY'), 'przyczepa Niewiadow B1300', 'BE');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Samochod ciezarowy', 'MAN ', 'TGL 12.220', 2019.0, 'AKTUALNY', to_date('4/02/2025', 'DD/MM/YYYY'), NULL, 'C');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Samochod ciezarowy', 'MAN ', 'TGL 12.250', 2020.0, 'AKTUALNY', to_date('10/02/2025', 'DD/MM/YYYY'), NULL, 'C');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Samochod ciezarowy', 'DAF ', 'LF', 2019.0, 'AKTUALNY', to_date('4/06/2024', 'DD/MM/YYYY'), NULL, 'C');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Samochod ciezarowy', 'MAN ', 'TGL 12 ', 2017.0, 'NIEAKTUALNY', to_date('5/02/2024', 'DD/MM/YYYY'), 'przyczepa typu tandem', 'CE');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Samochod ciezarowy', 'DAF', 'LF ', 2018.0, 'AKTUALNY', to_date('8/04/2024', 'DD/MM/YYYY'), 'przyczepa typu tandem', 'CE');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Autobus', 'Solbus ', 'ST 11', 2019.0, 'AKTUALNY', to_date('12/01/2025', 'DD/MM/YYYY'), NULL, 'D');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Ciagnik rolniczy', 'NEW HOLLAND ', 'T4.65 ', 2020.0, 'AKTUALNY', to_date('14/08/2024', 'DD/MM/YYYY'), 'przyczepa PRONAR T663/2', 'T');

INSERT INTO POJAZD (TYP, MARKA, MODEL, ROK_PRODUKCJI, STATUS_PRZEGLADU, TERMIN_NASTEPNEGO_PRZEGLADU, DANE_PRZYCZEPY, TYP_KATEGORII) 
VALUES ('Ciagnik rolniczy', 'ZETOR ', 'PROXIMA PLUS 80', 2019.0, 'AKTUALNY', to_date('8/04/2024', 'DD/MM/YYYY'), 'przyczepa MAR-POL MT 600', 'T');

COMMIT;

