SET DEFINE OFF

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (401.0, 'Wymiana klockow hamulocywch', 500.0, 'WYKONANA', to_date('5/01/2024', 'DD/MM/YYYY'), to_date('10/01/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (425.0, 'Wymiana tarcz', 1000.0, 'WYKONANA', to_date('11/01/2024', 'DD/MM/YYYY'), to_date('14/01/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (402.0, 'Wymiana oleju i filtrow', 300.0, 'WYKONANA', to_date('15/01/2024', 'DD/MM/YYYY'), to_date('19/01/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (424.0, 'Wymiana pompy paliwa', 1200.0, 'WYKONANA', to_date('20/01/2024', 'DD/MM/YYYY'), to_date('24/01/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (403.0, 'Wymiana opon', 250.0, 'W TRAKCIE', to_date('25/01/2024', 'DD/MM/YYYY'), NULL);

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (423.0, 'Wymiana swiec zaplonowych', 900.0, 'WYKONANA', to_date('30/01/2024', 'DD/MM/YYYY'), to_date('5/02/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (404.0, 'Montaz nowej rury wydechowej', 400.0, 'WYKONANA', to_date('10/02/2024', 'DD/MM/YYYY'), to_date('15/02/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (422.0, 'Wymiana katalizatora', 1500.0, 'WYKONANA', to_date('16/02/2024', 'DD/MM/YYYY'), to_date('20/02/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (405.0, 'Wymiana cewki', 300.0, 'WYKONANA', to_date('21/02/2024', 'DD/MM/YYYY'), to_date('25/02/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (421.0, 'Wymiana szby – przednia prawa', 400.0, 'W TRAKCIE', to_date('26/02/2024', 'DD/MM/YYYY'), NULL);

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (406.0, 'Wymiana wahacza', 650.0, 'DO ODBIORU', to_date('28/02/2024', 'DD/MM/YYYY'), to_date('2/03/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (420.0, 'Wymiana miski olejowej', 300.0, 'W TRAKCIE', to_date('1/03/2024', 'DD/MM/YYYY'), NULL);

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (407.0, 'Wymiana filtrow powietrza', 80.0, 'W TRAKCIE', to_date('4/03/2024', 'DD/MM/YYYY'), NULL);

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (419.0, 'Serwis klimatyzacji', 200.0, 'WYKONANA', to_date('10/12/2023', 'DD/MM/YYYY'), to_date('15/12/2023', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (408.0, 'Wymiana pompy paliwa', 1200.0, 'WYKONANA', to_date('5/12/2023', 'DD/MM/YYYY'), to_date('9/12/2023', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (418.0, 'Wymiana oleju i filtrow', 300.0, 'W TRAKCIE', to_date('26/02/2023', 'DD/MM/YYYY'), NULL);

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (409.0, 'Wymiana swiec zaplonowych', 900.0, 'WYKONANA', to_date('10/10/2023', 'DD/MM/YYYY'), to_date('12/10/2023', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (417.0, 'Wymiana opon', 250.0, 'WYKONANA', to_date('15/10/2023', 'DD/MM/YYYY'), to_date('20/10/2023', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (410.0, 'Wymiana oleju', 300.0, 'WYKONANA', to_date('21/10/2023', 'DD/MM/YYYY'), to_date('24/10/2023', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (416.0, 'Wymiana klockow hamulocywch', 500.0, 'WYKONANA', to_date('25/10/2023', 'DD/MM/YYYY'), to_date('27/10/2023', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (411.0, 'Wymiana klockow hamulocywch', 500.0, 'WYKONANA', to_date('6/01/2024', 'DD/MM/YYYY'), to_date('11/01/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (415.0, 'Wymiana tarcz', 1000.0, 'WYKONANA', to_date('12/01/2024', 'DD/MM/YYYY'), to_date('15/01/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (412.0, 'Wymiana oleju', 300.0, 'DO ODBIORU', to_date('16/01/2024', 'DD/MM/YYYY'), to_date('20/01/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (414.0, 'Wymiana pompy paliwa', 1200.0, 'W TRAKCIE', to_date('21/01/2024', 'DD/MM/YYYY'), NULL);

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (413.0, 'Wymiana opon', 250.0, 'W TRAKCIE', to_date('26/01/2024', 'DD/MM/YYYY'), NULL);

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (413.0, 'Wymiana swiec zaplonowych', 900.0, 'WYKONANA', to_date('31/01/2024', 'DD/MM/YYYY'), to_date('6/02/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (414.0, 'Montaz nowej rury wydechowej', 400.0, 'WYKONANA', to_date('11/02/2024', 'DD/MM/YYYY'), to_date('16/02/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (412.0, 'Wymiana opon', 1500.0, 'WYKONANA', to_date('17/02/2024', 'DD/MM/YYYY'), to_date('21/02/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (415.0, 'Wymiana cewki', 300.0, 'WYKONANA', to_date('22/02/2024', 'DD/MM/YYYY'), to_date('26/02/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (411.0, 'Wymiana swiec zaplonowych', 400.0, 'W TRAKCIE', to_date('27/02/2024', 'DD/MM/YYYY'), NULL);

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (416.0, 'Wymiana tarcz', 650.0, 'DO ODBIORU', to_date('29/02/2024', 'DD/MM/YYYY'), to_date('3/03/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (410.0, 'Wymiana miski olejowej', 300.0, 'W TRAKCIE', to_date('2/03/2024', 'DD/MM/YYYY'), NULL);

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (417.0, 'Wymiana filtrow powietrza', 80.0, 'W TRAKCIE', to_date('5/03/2024', 'DD/MM/YYYY'), NULL);

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (409.0, 'Wymiana opon', 200.0, 'WYKONANA', to_date('11/12/2023', 'DD/MM/YYYY'), to_date('16/12/2023', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (418.0, 'Wymiana pompy paliwa', 1200.0, 'WYKONANA', to_date('6/12/2023', 'DD/MM/YYYY'), to_date('10/12/2023', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (408.0, 'Wymiana oleju i filtrow', 300.0, 'DO ODBIORU', to_date('27/02/2023', 'DD/MM/YYYY'), to_date('2/03/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (419.0, 'Wymiana swiec zaplonowych', 900.0, 'WYKONANA', to_date('11/10/2023', 'DD/MM/YYYY'), to_date('13/10/2023', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (407.0, 'Wymiana opon', 250.0, 'WYKONANA', to_date('16/10/2023', 'DD/MM/YYYY'), to_date('21/10/2023', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (420.0, 'Wymiana oleju i filtrow', 300.0, 'WYKONANA', to_date('22/10/2023', 'DD/MM/YYYY'), to_date('25/10/2023', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (406.0, 'Wymiana klockow hamulocywch', 500.0, 'WYKONANA', to_date('26/10/2023', 'DD/MM/YYYY'), to_date('28/10/2023', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (421.0, 'Wymiana klockow hamulocywch', 500.0, 'WYKONANA', to_date('7/01/2024', 'DD/MM/YYYY'), to_date('12/01/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (405.0, 'Wymiana tarcz', 1000.0, 'WYKONANA', to_date('13/01/2024', 'DD/MM/YYYY'), to_date('16/01/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (422.0, 'Wymiana oleju i filtrow', 300.0, 'DO ODBIORU', to_date('17/01/2024', 'DD/MM/YYYY'), to_date('21/01/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (404.0, 'Wymiana pompy paliwa', 1200.0, 'WYKONANA', to_date('22/01/2024', 'DD/MM/YYYY'), to_date('28/01/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (423.0, 'Wymiana opon', 250.0, 'DO ODBIORU', to_date('27/01/2024', 'DD/MM/YYYY'), to_date('30/01/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (403.0, 'Wymiana swiec zaplonowych', 900.0, 'WYKONANA', to_date('1/02/2024', 'DD/MM/YYYY'), to_date('7/02/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (424.0, 'Montaz nowej rury wydechowej', 400.0, 'WYKONANA', to_date('12/02/2024', 'DD/MM/YYYY'), to_date('17/02/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (402.0, 'Wymiana katalizatora', 1500.0, 'WYKONANA', to_date('18/02/2024', 'DD/MM/YYYY'), to_date('22/02/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (425.0, 'Wymiana cewki', 300.0, 'WYKONANA', to_date('23/02/2024', 'DD/MM/YYYY'), to_date('27/02/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (401.0, 'Wymiana szby – przednia prawa', 400.0, 'W TRAKCIE', to_date('28/02/2024', 'DD/MM/YYYY'), NULL);

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (425.0, 'Wymiana wahacza', 650.0, 'DO ODBIORU', to_date('1/03/2024', 'DD/MM/YYYY'), to_date('4/03/2024', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (402.0, 'Wymiana miski olejowej', 300.0, 'W TRAKCIE', to_date('3/03/2024', 'DD/MM/YYYY'), NULL);

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (424.0, 'Wymiana filtrow powietrza', 80.0, 'W TRAKCIE', to_date('6/03/2024', 'DD/MM/YYYY'), NULL);

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (403.0, 'Serwis klimatyzacji', 200.0, 'WYKONANA', to_date('12/12/2023', 'DD/MM/YYYY'), to_date('17/12/2023', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (423.0, 'Wymiana pompy paliwa', 1200.0, 'WYKONANA', to_date('7/12/2023', 'DD/MM/YYYY'), to_date('11/12/2023', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (404.0, 'Wymiana oleju i filtrow', 300.0, 'W TRAKCIE', to_date('28/02/2023', 'DD/MM/YYYY'), NULL);

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (422.0, 'Wymiana swiec zaplonowych', 900.0, 'WYKONANA', to_date('12/10/2023', 'DD/MM/YYYY'), to_date('14/10/2023', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (405.0, 'Wymiana opon', 250.0, 'WYKONANA', to_date('17/10/2023', 'DD/MM/YYYY'), to_date('22/10/2023', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (423.0, 'Wymiana oleju i filtrow', 300.0, 'WYKONANA', to_date('23/10/2023', 'DD/MM/YYYY'), to_date('26/10/2023', 'DD/MM/YYYY'));

INSERT INTO NAPRAWA (ID_POJAZDU, OPIS, KOSZT, STATUS, DATA_ROZPCZECIA, DATA_ZAKONCZENIA) 
VALUES (406.0, 'Wymiana klockow hamulocywch', 500.0, 'WYKONANA', to_date('27/10/2023', 'DD/MM/YYYY'), to_date('29/10/2023', 'DD/MM/YYYY'));

COMMIT;