SET DEFINE OFF

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1000.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1001.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1002.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1003.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1004.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1005.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1006.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1007.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1008.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1009.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1010.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1011.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1012.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1013.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1014.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1015.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1016.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1017.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1018.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1019.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1020.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1021.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1022.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1023.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1024.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1025.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1026.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1027.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1028.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1029.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1030.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1031.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1032.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1033.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1034.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1035.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1036.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1037.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1038.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1039.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1040.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1041.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1042.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1043.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1044.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1045.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1046.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1047.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1048.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1049.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1050.0, 'UMOWA', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1000.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1001.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1002.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1003.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1004.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1005.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1006.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1007.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1008.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1009.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1010.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1011.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1012.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1013.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1014.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1015.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1016.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1017.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1018.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1019.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1020.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1021.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1022.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1023.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1024.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1025.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1026.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1027.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1028.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1029.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1030.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1031.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1032.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1033.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1034.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1035.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1036.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1037.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1038.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1039.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1040.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1041.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1042.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1043.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1044.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1045.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1046.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1047.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1048.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1049.0, 'FORMULARZ ZAPISU', NULL);

INSERT INTO DOKUMENT (ID_KURSANTA, TYP, OPIS) 
VALUES (1050.0, 'FORMULARZ ZAPISU', NULL);

COMMIT;
