SET DEFINE OFF

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1000.0, to_date('1/03/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1000.0, to_date('8/03/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1000.0, to_date('15/03/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1000.0, to_date('22/03/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1001.0, to_date('1/03/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1001.0, to_date('8/03/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'niezastosowanie sie do znaku');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1001.0, to_date('15/03/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1001.0, to_date('22/03/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1001.0, to_date('29/03/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1002.0, to_date('1/03/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1002.0, to_date('8/03/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1002.0, to_date('15/03/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1002.0, to_date('22/03/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'nieudane parkowanie');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1002.0, to_date('29/03/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1003.0, to_date('1/03/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'NIEZDANY', '5 blednych odpowiedzi');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1003.0, to_date('8/03/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1003.0, to_date('15/03/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1003.0, to_date('22/03/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1003.0, to_date('29/03/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'najechanie na tyczke');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1003.0, to_date('5/04/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1004.0, to_date('1/03/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1004.0, to_date('8/03/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1004.0, to_date('15/03/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1004.0, to_date('22/03/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1005.0, to_date('1/03/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1005.0, to_date('8/03/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'najechanie na tyczke');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1005.0, to_date('15/03/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1005.0, to_date('22/03/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1005.0, to_date('29/03/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1006.0, to_date('1/04/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1006.0, to_date('8/04/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1006.0, to_date('15/04/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1006.0, to_date('22/04/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'nieudane parkowanie');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1006.0, to_date('29/04/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1007.0, to_date('1/04/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'NIEZDANY', '8 blednych odpowiedzi');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1007.0, to_date('8/04/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1007.0, to_date('15/04/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1007.0, to_date('22/04/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1007.0, to_date('29/04/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'najechanie na tyczke');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1007.0, to_date('6/05/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1008.0, to_date('1/04/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1008.0, to_date('8/04/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1008.0, to_date('15/04/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1008.0, to_date('22/04/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1009.0, to_date('1/04/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1009.0, to_date('8/04/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'nieudane parkowanie');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1009.0, to_date('15/04/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1009.0, to_date('22/04/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1009.0, to_date('29/04/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1010.0, to_date('1/04/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1010.0, to_date('8/04/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1010.0, to_date('15/04/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1010.0, to_date('22/04/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'najechanie na tyczke');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1010.0, to_date('29/04/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1011.0, to_date('1/04/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'NIEZDANY', '5 blednych odpowiedzi');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1011.0, to_date('8/04/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1011.0, to_date('15/04/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1011.0, to_date('22/04/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1011.0, to_date('29/04/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'najechanie na tyczke');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1011.0, to_date('6/05/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1012.0, to_date('4/05/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1012.0, to_date('13/05/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1012.0, to_date('22/05/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1012.0, to_date('31/05/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1013.0, to_date('4/05/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1013.0, to_date('13/05/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'niezastosowanie sie do znaku');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1013.0, to_date('22/05/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1013.0, to_date('31/05/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1013.0, to_date('9/06/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1014.0, to_date('4/05/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1014.0, to_date('13/05/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1014.0, to_date('22/05/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1014.0, to_date('31/05/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'nieudane parkowanie');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1014.0, to_date('9/06/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1015.0, to_date('1/06/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'NIEZDANY', '5 blednych odpowiedzi');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1015.0, to_date('8/06/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1015.0, to_date('9/06/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1015.0, to_date('10/06/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1015.0, to_date('11/06/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'najechanie na tyczke');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1015.0, to_date('12/06/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1016.0, to_date('1/06/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1016.0, to_date('8/06/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1016.0, to_date('9/06/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1016.0, to_date('10/06/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1017.0, to_date('1/06/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1017.0, to_date('8/06/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'najechanie na tyczke');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1017.0, to_date('9/06/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1017.0, to_date('10/06/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1017.0, to_date('11/06/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1018.0, to_date('1/07/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1018.0, to_date('8/07/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1018.0, to_date('9/07/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1018.0, to_date('10/07/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'nieudane parkowanie');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1018.0, to_date('11/07/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1019.0, to_date('1/07/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'NIEZDANY', '5 blednych odpowiedzi');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1019.0, to_date('8/07/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1019.0, to_date('9/07/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1019.0, to_date('10/07/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1019.0, to_date('11/07/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'najechanie na tyczke');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1019.0, to_date('12/07/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1020.0, to_date('1/07/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1020.0, to_date('8/07/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1020.0, to_date('9/07/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1020.0, to_date('10/07/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1021.0, to_date('1/08/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1021.0, to_date('8/08/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'nieudane parkowanie');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1021.0, to_date('9/08/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1021.0, to_date('10/08/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1021.0, to_date('11/08/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1022.0, to_date('1/08/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1022.0, to_date('8/08/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1022.0, to_date('9/08/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1022.0, to_date('10/08/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'najechanie na tyczke');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1022.0, to_date('11/08/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1023.0, to_date('1/08/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'NIEZDANY', '5 blednych odpowiedzi');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1023.0, to_date('8/08/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1023.0, to_date('9/08/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1023.0, to_date('10/08/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1023.0, to_date('11/08/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'najechanie na tyczke');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1023.0, to_date('12/08/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1024.0, to_date('1/09/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1024.0, to_date('8/09/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1024.0, to_date('9/09/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1024.0, to_date('10/09/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1025.0, to_date('1/09/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1025.0, to_date('8/09/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'niezastosowanie sie do znaku');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1025.0, to_date('9/09/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1025.0, to_date('10/09/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1025.0, to_date('11/09/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1026.0, to_date('1/09/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1026.0, to_date('8/09/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1026.0, to_date('9/09/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1026.0, to_date('10/09/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'nieudane parkowanie');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1026.0, to_date('11/09/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1027.0, to_date('1/10/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'NIEZDANY', '5 blednych odpowiedzi');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1027.0, to_date('8/10/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1027.0, to_date('9/10/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1027.0, to_date('10/10/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1027.0, to_date('11/10/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'najechanie na tyczke');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1027.0, to_date('12/10/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1028.0, to_date('1/10/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1028.0, to_date('8/10/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1028.0, to_date('9/10/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1028.0, to_date('10/10/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1029.0, to_date('1/10/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1029.0, to_date('8/10/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'najechanie na tyczke');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1029.0, to_date('9/10/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1029.0, to_date('10/10/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1029.0, to_date('11/10/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1030.0, to_date('5/11/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1030.0, to_date('12/11/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1030.0, to_date('19/11/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1030.0, to_date('26/11/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'nieudane parkowanie');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1030.0, to_date('3/12/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1031.0, to_date('5/11/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'NIEZDANY', '8 blednych odpowiedzi');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1031.0, to_date('12/11/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1031.0, to_date('19/11/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1031.0, to_date('26/11/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1031.0, to_date('3/12/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'najechanie na tyczke');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1031.0, to_date('10/12/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1032.0, to_date('5/11/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1032.0, to_date('12/11/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1032.0, to_date('19/11/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1032.0, to_date('26/11/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1033.0, to_date('1/12/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1033.0, to_date('8/12/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'nieudane parkowanie');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1033.0, to_date('9/12/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1033.0, to_date('10/12/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1033.0, to_date('11/12/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1034.0, to_date('1/12/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1034.0, to_date('8/12/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1034.0, to_date('9/12/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1034.0, to_date('10/12/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'najechanie na tyczke');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1034.0, to_date('11/12/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1035.0, to_date('1/12/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'NIEZDANY', '5 blednych odpowiedzi');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1035.0, to_date('8/12/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1035.0, to_date('9/12/2023', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1035.0, to_date('10/12/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1035.0, to_date('11/12/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'najechanie na tyczke');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1035.0, to_date('12/12/2023', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1036.0, to_date('3/01/2024', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1036.0, to_date('10/01/2024', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1036.0, to_date('17/01/2024', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1036.0, to_date('24/01/2024', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1037.0, to_date('3/01/2024', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1037.0, to_date('10/01/2024', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'niezastosowanie sie do znaku');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1037.0, to_date('17/01/2024', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1037.0, to_date('24/01/2024', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1037.0, to_date('31/01/2024', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1038.0, to_date('3/01/2024', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1038.0, to_date('10/01/2024', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1038.0, to_date('17/01/2024', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1038.0, to_date('24/01/2024', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'nieudane parkowanie');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1038.0, to_date('31/01/2024', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1039.0, to_date('1/02/2024', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'NIEZDANY', '5 blednych odpowiedzi');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1039.0, to_date('8/02/2024', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1039.0, to_date('9/02/2024', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1039.0, to_date('10/02/2024', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1039.0, to_date('11/02/2024', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'najechanie na tyczke');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1039.0, to_date('12/02/2024', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1040.0, to_date('1/02/2024', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1040.0, to_date('8/02/2024', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1040.0, to_date('9/02/2024', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1040.0, to_date('10/02/2024', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1041.0, to_date('1/02/2024', 'DD/MM/YYYY'), 'WEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1041.0, to_date('8/02/2024', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'NIEZDANY', 'nieudane parkowanie');

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1041.0, to_date('9/02/2024', 'DD/MM/YYYY'), 'WEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1041.0, to_date('10/02/2024', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'TEORIA', 'ZDANY', NULL);

INSERT INTO EGZAMIN (ID_KURSANTA, DATA_EGZAMINU, TYP, RODZAJ, WYNIK, POWOD_NIEZALICZENIA) 
VALUES (1041.0, to_date('11/02/2024', 'DD/MM/YYYY'), 'ZEWNETRZNY', 'PRAKTYKA', 'ZDANY', NULL);

COMMIT;