SET DEFINE OFF

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1000.0, 4.0, 'dobry instruktor', 'wczesna godzina zajesc', 'pozniejsze godziny zajec');

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1001.0, 5.0, 'latwy kontakt z biurem', NULL, 'brak');

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1002.0, 4.0, NULL, NULL, NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1003.0, 4.0, 'dobry instruktor', NULL, NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1004.0, 3.0, NULL, 'trudny kontakt z insturktorem', NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1005.0, 5.0, 'latwy kontakt z biurem', NULL, NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1006.0, 5.0, 'solidne przygotowanie do egzaminu', NULL, 'dobrze by było wykonac telefon z przypomnieniem o dokonaniu wplaty');

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1007.0, 4.0, NULL, 'trudnosc w umoweniu godzin jazdy', NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1008.0, 5.0, NULL, NULL, NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1009.0, 5.0, 'latwy kontakt z biurem', NULL, 'pozniejsze godziny zajec');

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1010.0, 4.0, NULL, 'wyklady rozciagniete w czasie', NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1011.0, 5.0, 'dobry instruktor', NULL, NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1012.0, 4.0, NULL, NULL, NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1013.0, 4.0, 'solidne przygotowanie do egzaminu', NULL, 'dobrze by było wykonac telefon z przypomnieniem o dokonaniu wplaty');

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1014.0, 3.0, NULL, 'wyklady rozciagniete w czasie', NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1015.0, 5.0, 'latwy kontakt z biurem', NULL, NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1016.0, 5.0, NULL, NULL, 'brak');

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1017.0, 4.0, 'dobry instruktor', NULL, NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1018.0, 5.0, 'dobry instruktor', NULL, NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1019.0, 5.0, NULL, NULL, 'pozniejsze godziny zajec');

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1020.0, 4.0, NULL, 'wyklady rozciagniete w czasie', NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1021.0, 5.0, 'solidne przygotowanie do egzaminu', NULL, NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1022.0, 4.0, NULL, NULL, NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1023.0, 4.0, NULL, NULL, NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1024.0, 3.0, NULL, 'trudnosc w umoweniu godzin jazdy', NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1025.0, 5.0, 'latwy kontakt z biurem', NULL, NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1026.0, 5.0, NULL, 'wyklady rozciagniete w czasie', NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1027.0, 4.0, NULL, NULL, 'dobrze by było wykonac telefon z przypomnieniem o dokonaniu wplaty');

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1028.0, 5.0, 'dobry instruktor', NULL, 'brak');

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1029.0, 5.0, NULL, NULL, NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1030.0, 4.0, NULL, 'wczesna godzina zajec', 'pozniejsze godziny zajec');

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1031.0, 5.0, 'latwy kontakt z biurem', NULL, 'brak');

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1032.0, 4.0, NULL, NULL, NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1033.0, 4.0, 'dobry instruktor', NULL, NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1034.0, 3.0, NULL, 'wyklady rozciagniete w czasie', 'dobrze by było wykonac telefon z przypomnieniem o dokonaniu wplaty');

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1035.0, 5.0, 'solidne przygotowanie do egzaminu', NULL, NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1036.0, 5.0, 'dobry instruktor', NULL, 'brak');

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1037.0, 4.0, NULL, 'trudnosc w umoweniu godzin jazdy', NULL);

INSERT INTO ANKIETA (ID_KURSANTA, OCENA_W_SKALI_1DO5, POZYTYWY, NEGATYWY, SUGESTIE) 
VALUES (1038.0, 5.0, 'solidne przygotowanie do egzaminu', NULL, NULL);

COMMIT;