SET DEFINE OFF

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (10.0, 'A');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (10.0, 'B');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (11.0, 'B');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (11.0, 'C');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (11.0, 'CE');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (12.0, 'B');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (12.0, 'T');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (12.0, 'D');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (13.0, 'A');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (13.0, 'B');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (14.0, 'B');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (14.0, 'C');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (14.0, 'CE');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (15.0, 'B');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (15.0, 'T');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (16.0, 'A');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (16.0, 'B');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (16.0, 'C');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (16.0, 'D');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (17.0, 'B');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (17.0, 'C');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (18.0, 'B');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (18.0, 'C');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (18.0, 'CE');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (18.0, 'T');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (19.0, 'A');

INSERT INTO RELATION_2 (ID_INSTRUKTORA, TYP_KATEGORII) 
VALUES (19.0, 'B');

COMMIT;