DROP TABLE ANKIETA CASCADE CONSTRAINTS;

DROP TABLE DOKUMENT CASCADE CONSTRAINTS;

DROP TABLE EGZAMIN CASCADE CONSTRAINTS;

DROP TABLE INSTRUKTOR CASCADE CONSTRAINTS;

DROP TABLE KATEGORIA CASCADE CONSTRAINTS;

DROP TABLE KURS CASCADE CONSTRAINTS;

DROP TABLE KURSANT CASCADE CONSTRAINTS;

DROP TABLE NAPRAWA CASCADE CONSTRAINTS;

DROP TABLE OPLATA CASCADE CONSTRAINTS;

DROP TABLE POJAZD CASCADE CONSTRAINTS;

DROP TABLE RELATION_1 CASCADE CONSTRAINTS;

DROP TABLE RELATION_2 CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_ID_ANKIETY;

DROP SEQUENCE SEQ_ID_DOKUMENTU;

DROP SEQUENCE SEQ_ID_EGZAMINU;

DROP SEQUENCE SEQ_ID_INSTRUKTORA;

DROP SEQUENCE SEQ_ID_KURSU;

DROP SEQUENCE SEQ_ID_KURSANTA;

DROP SEQUENCE SEQ_ID_NAPRAWY;

DROP SEQUENCE SEQ_ID_OPLATY;

DROP SEQUENCE SEQ_ID_POJAZDU;

DROP VIEW KURSANT1015;

DROP VIEW PRACOWNIK_RECEPCJI;

DROP VIEW KIEROWNIK_OSRODKA;

DROP VIEW NADZORCA_POJAZDOW;

COMMIT;